<?php

namespace app\modules\car\controllers;

use app\modules\car\models\Car;
use app\modules\car\models\CarFrontSearch;
use app\modules\car\models\Category;
use app\modules\car\models\Vendor;
use Yii;
use yii\web\Controller;

class DefaultController extends Controller
{
    public function beforeAction($action)
    {
        $this->layout = '@app/views/layouts/main.php';

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new CarFrontSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $vendors = Vendor::getDropDownArray('id', 'title');
        $categories = Category::getDropDownArray('id', 'title');

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel'  => $searchModel,
            'vendors'      => $vendors,
            'categories'   => $categories,
        ]);
    }

    public function actionView($id)
    {
        $car = Car::find()
            ->with(['category', 'vendor'])
            ->andWhere(['id' => $id])
            ->one();

        return $this->render('view', [
            'model' => $car,
        ]);
    }
}
